---
- name: 'Wait for RPC port to be available'
  wait_for:
    port: '{{ nim_waku_rpc_tcp_port }}'
    delay: 5

- name: 'Extract address of the node for Consul'
  uri:
    url: 'http://localhost:{{ nim_waku_rpc_tcp_port }}/'
    method: POST
    body: 
      method: 'get_waku_v2_debug_v1_info'
      params: []
      jsonrpc: '2.0'
      id: 1
    status_code: 200
    body_format: json
  register: waku_info
  ignore_errors: true

- name: Verify we got the node address
  assert:
    that: 'waku_info.json.result.listenAddresses is defined'
    fail_msg: 'Did not receive Nim-Waku node address!'
    quiet: true

- name: Extract ENR address from resposne
  set_fact:
    nim_waku_discv5_enr_addr: |-
      {{ waku_info.json.result.get("enrUri", "unknown") }}

- name: Extract LibP2P TCP address from list
  set_fact:
    nim_waku_libp2p_multiaddr: |-
      {{ waku_info.json.result.listenAddresses
      | reject("contains", "/ws") | first }}

- name: Extract LibP2P WS address from list
  when: nim_waku_websocket_enabled or nim_waku_websockify_enabled
  set_fact:
    nim_waku_libp2p_websocket: |-
      {{ waku_info.json.result.listenAddresses
      | select("contains", "/ws") | first }}

- name: Extract peer ID from RPC response
  set_fact:
    nim_waku_peer_id: '{{ nim_waku_libp2p_multiaddr.split("/") | last }}'
